# 此文件已停用 - 目前使用 GCP Cloud Build 部署
# 如需重新啟用 Cloudflare Pages 部署，請移除下方註釋並配置相關 secrets
#
# name: Rebuild Site
# 
# on:
#   # 定時觸發：每天早上 8 點和晚上 8 點（UTC+8）
#   schedule:
#     - cron: '0 0,12 * * *'
#   
#   # 允許手動觸發
#   workflow_dispatch:
#   
#   # 當推送到 main 或 preview 分支時觸發
#   push:
#     branches:
#       - main
#       - preview
# 
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v3
#       
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#           cache: 'npm'
#       
#       - name: Install dependencies
#         run: npm ci
#       
#       - name: Build site
#         run: npm run build:cloudflare
#         env:
#           WORDPRESS_API_URL: ${{ secrets.WORDPRESS_API_URL }}
#           FRONTEND_DOMAIN: ${{ secrets.FRONTEND_DOMAIN }}
#       
#       - name: Deploy to Cloudflare Pages
#         uses: cloudflare/pages-action@v1
#         with:
#           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#           projectName: skincake
#           directory: out
#           gitHubToken: ${{ secrets.GITHUB_TOKEN }}
#           wranglerVersion: '3'